version: "3.6"

services:
  mysql:
    image: mysql:5.7.12
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - db-data:/var/lib/mysql
    env_file:
      - .env

    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

volumes:
  db-data:
